import {plural} from '@/shared/lib/plural';

export const lang = {
  hint: {
    password:
      'Пароль должен состоять минимум из 8 символов, содержать прописные и строчные буквы латинского алфавита, цифры и спецсимволы.',
    coordinatesFormat: 'Формат 00.000000',
  },
  rules: {
    required: 'Это поле обязательное',
    minLength: 'Минимальное значение символов: length',
    maxLength: 'Максимальное значение символов: length',
    domain: 'Введите корректное доменное имя',
    password_confirm: 'Пароли не совпадают',
    email: 'Неверный формат email',
    emailDuplicate: 'Такой email уже задан',
    unique: 'Такое значение уже существует. Поле должно быть уникальным',
    username: 'Имя может содержать только кириллицу',
    phone: 'Неправильный формат телефона',
    coords: 'Неправильный формат координат',
    incorrectSymbol: 'Поле содержит недопустимые символы',
    timePeriod: 'Неправильный формат времени',
    invalidTimePeriod: 'Время начала не может быть больше время окончания',
    blockTry: (count: number) =>
      `${plural(count, ['Осталась', 'Осталось', 'Осталось'])} ${count} ${plural(count, ['попытка', 'попытки', 'попытки'])}. Ваша учетная запись будет заблокирована или попробуйте повторить вход через 1 сутки.`,
  },
  field: {
    companyName: 'Название компании',
    login: 'Логин',
    password: 'Пароль',
    newPassword: 'Новый пароль',
    repeatPassword: 'Повторите пароль',
    email: 'Email',
    emailRecover: 'E-mail для восстановления',
    title: 'Название',
    title_en: 'Название на латинице',
    description: 'Описание',
    descriptionIsMainPage: 'Описание для главной страницы',
    createdAt: 'Дата создания',
    updatedAt: 'Дата изменения',
    author: 'Автор',
    legalName: 'Юридическое наименование',
    activeStatus: 'Статус активности',
    address: 'Адрес',
    sales: 'Продажи',
    service: 'Сервис',
    additionalPhone: 'Дополнительный',
    addPhone: 'Добавить номер',
    mainEmail: 'Основной e-mail',
    role: 'Роль',
    firstName: 'Имя',
    lastName: 'Фамилия',
    surName: 'Отчество',
    showBlocked: 'Показать заблокированных',
    showRead: 'Показать прочитанные',
    image_url: 'Ссылка на изображение',
    type: 'Тип',
  },
  btn: {
    signIn: 'Войти',
    register: 'Регистрация',
    rememberPassword: 'Забыли пароль',
    save: 'Сохранить',
    refreshData: 'Обновить данные',
    back: 'Назад',
    add: 'Добавить',
    delete: 'Удалить',
    more: 'Подробнее',
    edit: 'Редактировать',
    block: 'Заблокировать',
    create: 'Создать',
    cancel: 'Отменить',
    settingForm: 'Настройки формы',
    addMore: 'Добавить еще',
    activate: 'Активировать',
    unblock: 'Разблокировать',
    editSelection: 'Изменить выбор',
    close: 'Закрыть',
    acceptFilters: 'Применить фильтры',
    clearFilters: 'Сбросить фильтры',
    toSign: 'К авторизации',
    addEmail: 'Добавить e-mail',
  },
  title: {
    auth: 'Авторизация',
    register: 'Регистрация',
    priceElement: 'Информация о товаре',
    creatNewPriceItem: 'Создание нового товара',
    editPriceItem: 'Изменение товара',
    newPassword: 'Новый пароль',
    rememberPassword: 'Восстановление пароля',
    checkYourEmail: 'Проверьте почту',
    accountBlocked: 'Учетная запись заблокирована',
    userUnblocked: 'Пользователь разблокирован',
    passwordCreated: 'Пароль создан',
    passwordEdited: 'Пароль изменен',
    userBlocked: 'Пользователь заблокирован',
    serviceUnavailable: 'Сервис недоступен',
    siteContentList: 'Список контентных страниц сайта',
    basePrice: 'Основной прайс',
    FormList: 'Список доступных форм',
    FormRequest: 'Заявки по форме',
    siteDealersList: 'Список дилерских центров',
    deleteConfirm: 'Подтвердите удаление',
    createUser: 'Создание пользователя',
    createAdmin: 'Создание администратора дилерского центра',
    editing: 'Редактирование',
    aboutSite: 'О сайте',
    headerTitle: 'Logo Design Production',
    filter: 'Фильтры',
    userNotFound: 'Пользователь не найден',
    pageNotFound: 'Страница не найдена',
    admins: 'Администраторы',
    changesSave: 'Изменения сохранены',
    serverError: 'Произошла непредвиденная ошибка',
    error: 'Ошибка',
    additionalInfo: 'Дополнительная информация'
  },
  text: {
    perPage: 'Количество на странице:',
    selectFromList: 'Выберите из списка',
    selectDealer: 'Выберите дилера',
    selectRole: 'Выберите роль',
    notFound: 'Ничего не найдено',
    search: 'Поиск',
    dataNotFound: 'Данные не найдены',
    aboutPage: 'О странице',
    aboutUser: 'О пользователе',
    account: 'Учетная запись',
    extra: 'Дополнительно',
    phone: 'Телефоны',
    email: 'E-mail',
    filter: 'Фильтр',
    acceptDelete: 'Вы уверены что хотите удалить элемент'
  },
  cell: {
    id: 'ID',
    article: 'Артикул',
    image: 'Изображение',
    type: 'Тип',
    name: 'Название',
    brand: 'Бренд',
    deliveryTime: 'Срок поставки',
    quantity: 'Количество',
    price: 'Цена',
    purchasePrice: 'Закупочная цена',
    supplier: 'Поставщик',
    minOrderQty: 'Мин. для заказа'
  },
  notification: {
    resetPasswordEmailSent: 'На вашу почту :EMAIL: отправлено письмо для сброса пароля',
    passwordAttemptsExceeded:
      'Превышено количество попыток ввода пароля. Обратитесь к администратору для восстановления доступа',
    userUnblockedWithName: 'Пользователь userName разблокирован',
    generatedPasswordSent: 'Сгенерированный пароль отправлен на указанную почту',
    userBlockedWithName: 'Пользователь userName заблокирован',
    userUnBlockedWithName: 'Пользователь userName разблокирован',
    failedToConnectToService: 'Не удалось связаться с сервисом, попробуйте в другой раз',
    formatCoordinates: 'Формат 00.000000',
    formatPhone: 'Номер телефона должен содержать только цифры (без пробелов, скобок, тире и начинаться с 7)',
    incorrectLoginOrPassword: 'Неверный логин и пароль',
  },
  status: {
    read: 'Прочитан',
  },
  placeHolder: {
    statusSelect: 'Выберите статус',
    enterNumber: 'Введите число',
    selectType: 'Выберите тип',
  },
  label: {
    isMain: 'Сделать основным',
    listOrder: 'Очередность в списке',
    article: 'Артикул',
    name: 'Название',
    brand: 'Бренд',
    deliveryTime: 'Срок поставки',
    quantity: 'Количество',
    price: 'Цена',
    purchasePrice: 'Закупочная цена',
    supplier: 'Поставщик',
    minOrderQty: 'Мин. для заказа'
  },
};
